@startuml

skinparam classAttributeIconSize 0

class ConsultarTarefasUI{
}

class ConsultarTarefasController{
+obterListaTarefasPendentes()
+pesquisarTarefa()
+ordenarTarefa()
}

class RepositorioTarefas{
+obterListaTarefasPendentes()
}

ConsultarTarefasUI ..> ConsultarTarefasController
ConsultarTarefasController ..> RepositorioTarefas


@enduml