@startuml

autonumber
actor "Colaborador" as colab

participant ":ConsultarTarefasUI" as ui
participant ":ConsultarTarefasController" as ctrl
participant ":RepositorioTarefas" as repo

activate colab

colab -> ui : solicita consultar as tarefas pendentes ao colaborador

activate ui

ui -> ctrl : obterListaTarefasPendentes()

activate ctrl

ctrl -> repo : obterListaTarefasPendentes()

activate repo

deactivate ctrl

deactivate repo

ui --> colab : apresenta uma lista das tarefas pendentes

deactivate ui

opt

colab -> ui : pesquisa as tarefas pendentes

activate ui

ui -> ctrl : pesquisarTarefa()

activate ctrl

deactivate ui

deactivate ctrl

end

opt

colab -> ui : ordenar as tarefas pendentes

activate ui

ui -> ctrl : ordenarTarefa()

activate ctrl

deactivate ui

deactivate ctrl

end

@enduml