@startuml

autonumber
actor "Colaborador" as colab

participant ":ConsultarTarefasUI" as ui
participant ":ConsultarTarefasController" as ctrl
participant ":PersistenceContext" as persistence
participant "repoTarefas :RepositorioTarefas" as repo


activate colab

colab -> ui : solicita consultar as tarefas pendentes ao colaborador

activate ui

activate ctrl

ctrl -> persistence : repoColab = colaboradorRepositorio()

group sd if

ctrl -> ctrl : SystemUser sysUser = userSession.authenticatedUser()

end

activate persistence

deactivate persistence

ui -> ctrl : obterListaTarefasPendentes()

ctrl -> repo : listTarefasPend = obterListaTarefasPendentes()

activate repo

deactivate ctrl

deactivate repo

ui --> colab : apresenta uma lista das tarefas pendentes

deactivate ui

opt

colab -> ui : solicita um filtro nas tarefas pendentes

activate ui

ui -> ctrl : filtrarTarefa()

activate ctrl

ctrl -> repo : filtrarTarefa()

activate repo

deactivate repo

deactivate ctrl

ui --> colab : apresenta a filtragem das tarefas pendentes

deactivate ui

deactivate ui

end

opt

colab -> ui : solicita uma ordenação das tarefas pendentes

activate ui

ui -> ctrl : ordenarTarefa()

activate ctrl

ctrl -> repo : ordenarTarefa()

activate repo

deactivate repo

deactivate ctrl

ui --> colab : apresenta a lista das tarefas pendentes ordenada

deactivate ui

end

@enduml